server:
  port: 8010
spring:
  application:
    name: CITY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

